### ISSUE TITLE
Unclear attribution + ...

### ISSUE THREAD

**Issue by HyperSoop** [TheBossMagnus/Quilt-Optimized#8]
i don't care that much anyway, but since my attention was brought to your modpack recently, i'll leave a message here  
It's not very clear what your modpack has to do with SO, and it's linked on GitHub, but not on Modrinth. additionally, the modpack's description doesn't clearly describe what its goal is, which goes against Modrinth's content rules, specifically rule 2.  

You can't claim an increase in FPS over SO and FO without making sure all options that in any way affect visuals are set to be the same in all of them (Increasing performance at the cost of visuals is not optimization). Clouds and mipmap levels, all that should be the same across modpacks you're testing, and the settings you chose should be described near your tests as well as screenshots of your testing area.

**Comment by TheBossMagnus** [comment]
> It's not very clear what your modpack has to do with SO

SO gave me the idea to create a modpack and, especially in the early phase of development I took some tweaks/mods from them. I'll clarify this in Readme

> and it's linked on GitHub
I messed up, now it's fixed

> the modpack's description doesn't clearly describe what its goal is, which goes against Modrinth's content rules, specifically rule 2.

The description is a little too vague, but I wouldn't define it as misleading... I'm going to change it to avoid issues 


> Increasing performance at the cost of visuals is not optimization

I don't 100% agree. Optimize IMO means making something more efficient or functional, and reducing details can make MC more efficient/functional in some use cases (slightly boost FPS on lowest end HW)


> Clouds and mipmap levels, all that should be the same across modpacks you're testing, and the settings you chose should be described near your tests as well as screenshots of your testing area.
As of now, I'll add a clear statement under benchmarks. in the future, I'll redo all testing more "fairly" and also using another different setup.

> should be described near your tests as well as screenshots of your testing area.
I forgot to add the map/seed used in linked spreadsheets, now is fixed!

Thank you for your tips and remarks!
